# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 800a96bff7690f417991bb1ffbc2ec170d5aa64e4c6ead5001c83ce25bacb62e67fe785d8a23bccfc39b4c32883f1750dfb00452129027596deca36469d62ca3

test:
  secret_key_base: 36f919df050e153c0aba103a196208f4a54ee2e55ea3fe2e07aea0743ae41eac958bdcc8b7188585ec5b34897b5fa1096ac0f3b39c07eff2533eed4cbc70dfc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
